sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: YMLOUvqenVwUtfaEQO2tKxXqlUCZeJkHCVWJPSyQ/Z8mdMlxpO/X/cHYvb6jd5AEYgNQ4JiBB87usGQSEOiyhgEipkF0JLGB78jx7nO8Ik0XkyKp3ypmp1F/WqSKp7lt4gLqs9AEkieLJF+PI2VrDCpBjMnAkuu2XsGOog70JY86j4v1/EHx6Ukjk8bsq6cixbyWfvYGVI4Mu0Lg7tM036AONwqZTZnfVvzy13fT3lWTNJp33MxFxOw1Y3JpT45TN2mGmzvPBpRncXjjChW+ixL19ZN1yOPtXJ5H1E6rIePH0+ussu6809O6S93TX07r3iNDBJRrZ9zX9OTJap1KkmsGh39B8lKCMdH1WyHxlURZqDydVr1uQbagssUrGHkcQpavAYf7jtq35x25C1napzO8NiBcx0X6NhTAZKNkdTGp8+vk/ypvWo1jNyJ7cnEPUcM9w/sB3kQqAuISpLzZSibWujDDtUk7MwMj58Xt1dC19eV5VDui2gxQU+A1IxaCZgURz6gg/pzl/IqvbDNpNh35IKJ/wYhoI9zlaopwkvIVeoPyaeyzVU+GkuTJPKauhGsKKMFcN2V7CgvnLkHc1c+CLGctfjDigl93w8kxHojFOuJ8f+5gfHPBxrnXA8Enl0Ig1+QP/mII13OC5ceBKnLTFCEnec88/l8L/K/z6X4=
  - secure: T9/SzrZt/PdiRDXUwBcf0F90vE8vzMGyd1Ppf72UmuPhuLBB4brRCympJIlYSalVwaMh6WhHu+mE5IChSm6eM+GVaMbkTz89+7xt2p5iQURNf+DDSM4HRH56mncRtbaFWNmkMmXpoYtzggRP8Rz85A36coHZ729znWPo7Yv4PUfV/caY0VyjKWY1reoFnlGNOxUMlbq7Q1ubAL0k9CwtG/miXWbzwU5GSjuSBWPqjai4iNcEIN6kbYfmUi2LttjMiRGqBPREZAxP0e1ds7oHtmlFO8/rdsBhYrsSC0nnjBNbvAfeYuzK0AMMKgDhkBw9LkxBp9gZjO3u90c5XceFA3OZEdiDMsiKDqthAwO/E2Kiq80M8Je4kmQQ0+4hdggwYDqUuObeHI6DXaMij2vCfDw+NgBt8u64ITsqE9xevx2ZN1Qa2H1p8qozFIZmztKP81PnXPfJN46gjCq5lMcLWsmBoFgZFdVa1lHNS1+hfeSkZuaatKvKdpAgnM8clt8u29tjSWIKmHLhu/EVqJKkxqbzSRSMlLhTl+bjAMvEr0Uluns2F6S8rDja6vqxq/0Sf9qXtvdlIcPEL3WvVTV0JVQ6iclllF4qcenb2R5jFaiKX4D/NrWQh69mSmJ/BmeV3Agfya/FI8ZM7FZliaKdfNhIAdlQ3LZ4e08m0jfFxik=
branches:
  only:
  - master
