sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: Np4emfG3CqDamaCr2aS1dafjJALGbk/KaQawjisKJUqtxj3w5acr8VC+yWjW9l6kfVp5yACSruRfs+KTMoueRykIO/9ILlYHCTZwbA5TjrmaAb4dDWu3xW5Wm/KYmK5slqNsh2Jk+o2C6k/JGEMm8/4OdEaCm7mXNJd7f3z9X13bAyqABXvRrMZtLR3W4OLybtpz5D9HzulaqVzC9e0PM6vYnpab9MU7UkzwbLVOxCUiWQ4SOEnF8A6QD1ll54bglRC+lF2GP5mh/3tu+78dk9eQhljpIN0diMOkHNazPjKy7MNodXd2oVpJqZ6e6zcFFxUFFRXt+3WuZBn0Q9LTcqbjTVpgdsVhuV+TcF5zTqfBL8fILyfKUw5J5JJMbGjcydLCHmfMRyG+xtFmU6JeLKgOWCbaMysTRQQV3SO+0I7rCvJ/QOL00IRA4hqqyMEKcOax19uFB6OMk8OrMBxVwIhK27fSVvPp2Mr5uiVghRcbcl3R3gcQjaXXcFV+9fsARA3ny+giin9LEHR+XrIMxOW4BoDtJv1o0WHlYa4Z9qX0joPCxbdsat921gOkW0HxDpDM+C5Do8SAnLAOvPkNMiL88PlSywwvzXUhJQLKIdEaIllUihSpFyeeV1rN0nZDSd83wU1KJfYuJ8WDW5M8wSGLKvEdQdqiAMTWGKrK6QY=
branches:
  only:
  - master
