sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: tKxna60mroGOQF06uTYMfUYHbXrCOyW8YJO1vsbaR43JtaXIv9dUQNF89ns8+nJl8XH9fpZ7lAAw2s6eIoRpjJdwwWMqE6qEv/8qsySrd4ughmKX6Hhg46d+i3ZZF63WDTsGUAU7qkv3/bOOXoumNu5Lk/zcJEwNYXR22hmNDxdSIPSCI6h/i0qGasROfYtcBCc+cIpRcmoch7A/i0GtCRTlZy8LaNSkAk3AHkVMTHmTCtXYg7CzQDUt26+F55XEaQcd58JhJv91sxmX2Ay+vOlBBI3GVp4eYUmTwciwSUbTIBHjugny14E+QyH0ZM02hujO1mOJniTX2E0MUIroQYv5bI3G9A2HS2yyF6rt3iN99ChkueZ4sU87O0VdgLzrmBN5sD2x/8Cd1tnmZi6y4qbivPs3hNjHEB2GGnsX2hc/sq681gzNSLP7xGOpgcshhq2UD4SFTxEJ2uSlFT/JuiF4W6GcW79oWdDtGbAT4zaA0qCAOeGtU/7CDtO3lgyd/vWSfbV9gGGR83635GSMXny06X7lDz6s+YeBHqhxN2cDojjQdtKrf9NcihNKU6qIDVT4rsyrMVRjf45WQTXgZV88lJ/gTo0aAIL8zX4XhswG0zBRj6tkbZ7/Z7d599lZujYjTAcmyIMRVPd6QktuAqI8fjhUD7/97MvczE59D4I=
branches:
  only:
  - master
