sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: cGlS9LdiJShwkosZMl2NF+uTosfDXbxooLZXWXYwI2V98g8tKHVnbtVrQbbCP/79FJ/FomW3InY21MOFosCd2L+9q4WJhRPL/17zOBABM9bNd+qFRZ6NhsltCuGLtBugBOW/MZi0DH4Zofg8W8Tx/A2w8sSVTajOEijvCZdDvk12kwkTr8v4tKfJFT+qG2W/7a9hgIp3zDsjh7uA9+MxiQ5xV8bPWtr634NLrMg13gc9DarjllG53m5zX9aWbaD4ewjlm0USFV2PjHTh855k34M1o+99RjWVgaDbl4JW36lNETn8PJqsl+uH5En3jR+mrBuQyS2ryhQ9+TJSuKUluFnQMPNVLDmjLOSB5Yg/K7HpWt4L9A5lzz27ossPpSflKPzrNlhTLlQj+1QxDiPYLn/5xS5PJ0HsxUzi/aswuJ+4wfq1OB96MXZGTps4WaWyuX8PtIuVBoOqJajnuU9cWlz8g9TFdIiPAvWfzx9WwKT2+SiqlkraGxJrcjowo9zs7Mu1R7S9GgzHOmZIUmX2FNJK+bx3EcQ/DQASWESZ2ziOFg6id/HqxXmtajBPWv/kqCAyX5oF4/tdciT15jskWRPpo2U/UnthMpEIfOCMAOrl1HBQcf/T/KnfJ1x6KqBwaqu2esBY68sZfg1EYuzyMVxiU7wtIC8KcI6RwgljfPk=
branches:
  only:
  - master
