sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: OPmk9LfEUh28pIelC2Id1nMD9Hklc6FMpsPPlJYNALxq5psA6eylamN3TMNBQCkGY5pzo3KZ8vqwQoKJieEhdc5J4qWmtfw1tUfijdHp0HVhprB8H1PvBP6g0FLT/6HwMgeSBNpNi0WIZ93h23fU25wAdNUqyaYA3xcgA4piJzdPov/mJKCqOiDRudHe+rokUGbBykOp7FVCeXgKxoJpb8HFNOLb3AkYKHQW0o+WdkN2MkwbzubUXbkqbHi+0m1WgEpoHm4pZhGLMyNozZkbrsMAtdesHxr1thUU8wrQ67JxbXOOb3Sd7Bd9VFApjQUnriAM22gpF+Dhhiya7uAYKor19s5AHqlRE/PilEUT+2yOdSp8EV3miqwvR87L2xQULdYLJ/Ce2Z4WNiR/Ltn2FsdDeC6sxKGF4ATH1/jwzQLokbUcf3YAFwKlBlqPsCJNYCsET/MHOG0267M0bI6vD37XHYowpnZbs2KNfJR7NJhMcCQ3rT3D2x7/kqeD4tH5Oe9Wu7Fon+Z5G7zsHWdHf4H0AxjY53z2IUjPsR1mDsKJU/9paGwF4yb683WFI/AFoarkST0LqNfgCx3RJ0eRWUPHaavMF6lJNnxxb2MKVb/QrgCqkJje1vK+SqIxv7miG4DQhhgV0whp9dNukNOfWKjNMy438eXxXUkTqhiGFzY=
branches:
  only:
  - master
