sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: YMLOUvqenVwUtfaEQO2tKxXqlUCZeJkHCVWJPSyQ/Z8mdMlxpO/X/cHYvb6jd5AEYgNQ4JiBB87usGQSEOiyhgEipkF0JLGB78jx7nO8Ik0XkyKp3ypmp1F/WqSKp7lt4gLqs9AEkieLJF+PI2VrDCpBjMnAkuu2XsGOog70JY86j4v1/EHx6Ukjk8bsq6cixbyWfvYGVI4Mu0Lg7tM036AONwqZTZnfVvzy13fT3lWTNJp33MxFxOw1Y3JpT45TN2mGmzvPBpRncXjjChW+ixL19ZN1yOPtXJ5H1E6rIePH0+ussu6809O6S93TX07r3iNDBJRrZ9zX9OTJap1KkmsGh39B8lKCMdH1WyHxlURZqDydVr1uQbagssUrGHkcQpavAYf7jtq35x25C1napzO8NiBcx0X6NhTAZKNkdTGp8+vk/ypvWo1jNyJ7cnEPUcM9w/sB3kQqAuISpLzZSibWujDDtUk7MwMj58Xt1dC19eV5VDui2gxQU+A1IxaCZgURz6gg/pzl/IqvbDNpNh35IKJ/wYhoI9zlaopwkvIVeoPyaeyzVU+GkuTJPKauhGsKKMFcN2V7CgvnLkHc1c+CLGctfjDigl93w8kxHojFOuJ8f+5gfHPBxrnXA8Enl0Ig1+QP/mII13OC5ceBKnLTFCEnec88/l8L/K/z6X4=
branches:
  only:
  - master
